spring:
  application:
    name: FESTIVAL-TICKETS-SERVICE
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5444/postgres
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  config:
    activate:
      on-profile: dev
    import: optional:configserver:http://localhost:8085
  cloud:
    config:
      fail-fast:true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health, circuitbreakerevents
    endpoint:
      health:
        show-details: always
    health:
      curcuitbreakers:
        enabled: true

resilience4j:
  circuitbreaker:
    instances:
      artists-service:
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 4
        minimumNumberOfCalls: 1
        eventConsumerBufferSize: 20
        registerHealthIndicator: true
        permittedNumberOfCallsInHalfOpenState: 3
  retry:
    instances:
      artists-service:
        maxAttempts: 3
        waitDuration: 10s

server:
  port: 8081